// server/data.js

const POSITIONS_DATA = [
  {
    id: 1,
    priority: "Urgent",
    type: "Existing - Attrition",
    client: "Bank of New York Mellon",
    opportunity: "Cloud Migration Phase 2",
    probability: 100,
    estStartDate: "2026-03-01",
    estEndDate: "2026-12-31",
    serviceLine: "App Dev",
    practice: "Banking",
    deliveryUnit: "BFSI",
    role: "Java Developer",
    careerLevel: "Sr",
    location: "India",
    skill: "Java, Spring Boot",
    fulfillment: "Internal",
    status: "Open",
    externalReqId: "REQ-2024-001",
    createDate: "2026-01-15",
    notes: "Replacement for Amit K."
  },
  {
    id: 2,
    priority: "High",
    type: "Closed Won - New Work",
    client: "Wells Fargo & Company",
    opportunity: "Payment Gateway Modernization",
    probability: 100,
    estStartDate: "2026-02-15",
    estEndDate: "2026-08-30",
    serviceLine: "App Dev",
    practice: "Banking",
    deliveryUnit: "BFSI",
    role: "React Lead",
    careerLevel: "Lead",
    location: "US",
    skill: "React, Node.js",
    fulfillment: "External",
    status: "Open",
    externalReqId: "REQ-WF-992",
    createDate: "2026-01-20",
    notes: "Client requested onshore lead"
  },
  {
    id: 3,
    priority: "Medium",
    type: "Pipeline - New Work",
    client: "Google, Inc.",
    opportunity: "AI Customer Support Bot",
    probability: 60,
    estStartDate: "2026-04-01",
    estEndDate: "2026-10-01",
    serviceLine: "Data",
    practice: "Banking",
    deliveryUnit: "TMT",
    role: "Data Scientist",
    careerLevel: "Jr",
    location: "Remote",
    skill: "Python, PyTorch",
    fulfillment: "Internal",
    status: "On Hold",
    externalReqId: "",
    createDate: "2026-02-01",
    notes: "Waiting for SOW signature"
  },
  {
    id: 4,
    priority: "High",
    type: "Existing - New Roles",
    client: "Amazon.com, Inc.",
    opportunity: "Logistics Optimization",
    probability: 90,
    estStartDate: "2026-03-15",
    estEndDate: "2026-12-15",
    serviceLine: "Cloud",
    practice: "Retail",
    deliveryUnit: "Retail & Consumer",
    role: "DevOps Engineer",
    careerLevel: "Sr",
    location: "US",
    skill: "AWS, Kubernetes, Terraform",
    fulfillment: "External",
    status: "Open",
    externalReqId: "AMZ-LOG-44",
    createDate: "2026-02-02",
    notes: "Requires AWS certification"
  },
  {
    id: 5,
    priority: "Urgent",
    type: "Closed Won - Extension",
    client: "Ford Motor Company",
    opportunity: "EV Battery Analytics",
    probability: 100,
    estStartDate: "2026-02-20",
    estEndDate: "2026-11-20",
    serviceLine: "Data",
    practice: "Auto",
    deliveryUnit: "Auto & Industrials",
    role: "Data Engineer",
    careerLevel: "Sr",
    location: "India",
    skill: "Spark, Databricks, Python",
    fulfillment: "Internal",
    status: "Open",
    externalReqId: "FORD-EV-09",
    createDate: "2026-01-25",
    notes: "Critical path for Q2 release"
  },
  {
    id: 6,
    priority: "Low",
    type: "Pipeline - Extensions",
    client: "Johnson & Johnson",
    opportunity: "Clinical Trials Dashboard",
    probability: 50,
    estStartDate: "2026-05-01",
    estEndDate: "2026-12-31",
    serviceLine: "App Dev",
    practice: "Healthcare",
    deliveryUnit: "HCLS",
    role: "Frontend Developer",
    careerLevel: "Jr",
    location: "Remote",
    skill: "Angular, RxJS",
    fulfillment: "Internal",
    status: "On Hold",
    externalReqId: "",
    createDate: "2026-02-03",
    notes: "Budget approval pending"
  },
  {
    id: 7,
    priority: "Medium",
    type: "Existing - Attrition",
    client: "Citibank",
    opportunity: "Wealth Management UI",
    probability: 100,
    estStartDate: "2026-03-10",
    estEndDate: "2026-09-10",
    serviceLine: "App Dev",
    practice: "Banking",
    deliveryUnit: "BFSI",
    role: "Full Stack Developer",
    careerLevel: "Lead",
    location: "LatAm",
    skill: "Java, Angular, Oracle",
    fulfillment: "Internal",
    status: "Open",
    externalReqId: "CITI-WLTH-01",
    createDate: "2026-02-01",
    notes: "Spanish speaker preferred"
  },
  {
    id: 8,
    priority: "High",
    type: "Prospective Demand",
    client: "Meta Platforms, Inc.",
    opportunity: "Metaverse Commerce Integration",
    probability: 40,
    estStartDate: "2026-06-01",
    estEndDate: "2026-12-31",
    serviceLine: "App Dev",
    practice: "Retail",
    deliveryUnit: "TMT",
    role: "Unity Developer",
    careerLevel: "Principal",
    location: "US",
    skill: "C#, Unity3D, VR",
    fulfillment: "External",
    status: "On Hold",
    externalReqId: "",
    createDate: "2026-02-04",
    notes: "Niche skill set required"
  },
  {
    id: 9,
    priority: "Urgent",
    type: "Closed Won - New Work",
    client: "Bank of New York Mellon",
    opportunity: "Regulatory Reporting overhaul",
    probability: 100,
    estStartDate: "2026-03-01",
    estEndDate: "2026-08-31",
    serviceLine: "Data",
    practice: "Banking",
    deliveryUnit: "BFSI",
    role: "Business Analyst",
    careerLevel: "Sr",
    location: "India",
    skill: "SQL, Tableau, Finance Domain",
    fulfillment: "Internal",
    status: "Open",
    externalReqId: "BNYM-REG-88",
    createDate: "2026-01-28",
    notes: ""
  },
  {
    id: 10,
    priority: "Medium",
    type: "Existing - New Roles",
    client: "Wells Fargo & Company",
    opportunity: "Mobile App Security",
    probability: 80,
    estStartDate: "2026-04-15",
    estEndDate: "2026-10-15",
    serviceLine: "QA",
    practice: "Banking",
    deliveryUnit: "BFSI",
    role: "Security Tester",
    careerLevel: "Sr",
    location: "US",
    skill: "Penetration Testing, OWASP",
    fulfillment: "External",
    status: "Open",
    externalReqId: "WF-SEC-22",
    createDate: "2026-02-02",
    notes: ""
  },
  {
    id: 11,
    priority: "Low",
    type: "Pipeline - New Work",
    client: "Google, Inc.",
    opportunity: "Cloud Infrastructure Audit",
    probability: 30,
    estStartDate: "2026-07-01",
    estEndDate: "2027-01-01",
    serviceLine: "Cloud",
    practice: "Banking",
    deliveryUnit: "TMT",
    role: "Cloud Architect",
    careerLevel: "Principal",
    location: "Remote",
    skill: "GCP, Security, Compliance",
    fulfillment: "Internal",
    status: "On Hold",
    externalReqId: "",
    createDate: "2026-02-05",
    notes: "Early discussions"
  },
  {
    id: 12,
    priority: "High",
    type: "Closed Won - Extension",
    client: "Ford Motor Company",
    opportunity: "Supply Chain Digital Twin",
    probability: 100,
    estStartDate: "2026-03-01",
    estEndDate: "2026-12-31",
    serviceLine: "App Dev",
    practice: "Auto",
    deliveryUnit: "Auto & Industrials",
    role: "Backend Developer",
    careerLevel: "Sr",
    location: "India",
    skill: "Node.js, MongoDB, Kafka",
    fulfillment: "Internal",
    status: "Open",
    externalReqId: "FORD-SC-55",
    createDate: "2026-01-30",
    notes: ""
  },
  {
    id: 13,
    priority: "Urgent",
    type: "Existing - Attrition",
    client: "Amazon.com, Inc.",
    opportunity: "Prime Video Search",
    probability: 100,
    estStartDate: "2026-02-25",
    estEndDate: "2026-08-25",
    serviceLine: "Data",
    practice: "Retail",
    deliveryUnit: "Retail & Consumer",
    role: "Search Engineer",
    careerLevel: "Lead",
    location: "US",
    skill: "ElasticSearch, Solr, Java",
    fulfillment: "External",
    status: "Open",
    externalReqId: "AMZ-SRCH-12",
    createDate: "2026-02-01",
    notes: "Backfill for Sarah L."
  },
  {
    id: 14,
    priority: "Medium",
    type: "Pipeline - Extensions",
    client: "Johnson & Johnson",
    opportunity: "SAP S/4HANA Migration",
    probability: 70,
    estStartDate: "2026-04-01",
    estEndDate: "2027-04-01",
    serviceLine: "Management",
    practice: "Healthcare",
    deliveryUnit: "HCLS",
    role: "Project Manager",
    careerLevel: "Manager",
    location: "India",
    skill: "SAP, PMP, Agile",
    fulfillment: "Internal",
    status: "Open",
    externalReqId: "JJ-SAP-99",
    createDate: "2026-01-20",
    notes: ""
  },
  {
    id: 15,
    priority: "Low",
    type: "Existing - New Roles",
    client: "Citibank",
    opportunity: "Credit Card Rewards Platform",
    probability: 90,
    estStartDate: "2026-03-20",
    estEndDate: "2026-09-20",
    serviceLine: "QA",
    practice: "Banking",
    deliveryUnit: "BFSI",
    role: "Automation Tester",
    careerLevel: "Jr",
    location: "LatAm",
    skill: "Selenium, Java, Jenkins",
    fulfillment: "Internal",
    status: "Open",
    externalReqId: "CITI-QA-04",
    createDate: "2026-02-03",
    notes: ""
  },
  {
    id: 16,
    priority: "High",
    type: "Closed Won - New Work",
    client: "Meta Platforms, Inc.",
    opportunity: "Data Center Optimization",
    probability: 100,
    estStartDate: "2026-03-01",
    estEndDate: "2026-09-01",
    serviceLine: "Cloud",
    practice: "Retail",
    deliveryUnit: "TMT",
    role: "Network Engineer",
    careerLevel: "Sr",
    location: "Remote",
    skill: "Cisco, Python, Ansible",
    fulfillment: "External",
    status: "Open",
    externalReqId: "META-NET-33",
    createDate: "2026-01-29",
    notes: ""
  },
  {
    id: 17,
    priority: "Medium",
    type: "Pipeline - New Work",
    client: "Wells Fargo & Company",
    opportunity: "Blockchain Identity Pilot",
    probability: 50,
    estStartDate: "2026-05-15",
    estEndDate: "2026-11-15",
    serviceLine: "App Dev",
    practice: "Banking",
    deliveryUnit: "BFSI",
    role: "Blockchain Developer",
    careerLevel: "Sr",
    location: "US",
    skill: "Solidity, Ethereum, Go",
    fulfillment: "External",
    status: "On Hold",
    externalReqId: "",
    createDate: "2026-02-05",
    notes: "Waiting on regulatory clarity"
  },
  {
    id: 18,
    priority: "Urgent",
    type: "Existing - Attrition",
    client: "Bank of New York Mellon",
    opportunity: "Legacy Mainframe Support",
    probability: 100,
    estStartDate: "2026-02-28",
    estEndDate: "2026-12-31",
    serviceLine: "App Dev",
    practice: "Banking",
    deliveryUnit: "BFSI",
    role: "Mainframe Developer",
    careerLevel: "Sr",
    location: "India",
    skill: "COBOL, JCL, DB2",
    fulfillment: "Internal",
    status: "Open",
    externalReqId: "BNYM-MF-01",
    createDate: "2026-01-15",
    notes: "Hard to find skill"
  },
  {
    id: 19,
    priority: "Low",
    type: "Prospective Demand",
    client: "Google, Inc.",
    opportunity: "Android Automotive OS",
    probability: 25,
    estStartDate: "2026-08-01",
    estEndDate: "2027-08-01",
    serviceLine: "App Dev",
    practice: "Auto",
    deliveryUnit: "TMT",
    role: "Embedded Engineer",
    careerLevel: "Lead",
    location: "US",
    skill: "C++, Linux, Android HAL",
    fulfillment: "External",
    status: "On Hold",
    externalReqId: "",
    createDate: "2026-02-05",
    notes: "RFP response in progress"
  },
  {
    id: 20,
    priority: "High",
    type: "Existing - New Roles",
    client: "Johnson & Johnson",
    opportunity: "Medical Device IoT",
    probability: 95,
    estStartDate: "2026-03-01",
    estEndDate: "2026-09-01",
    serviceLine: "Cloud",
    practice: "Healthcare",
    deliveryUnit: "HCLS",
    role: "IoT Architect",
    careerLevel: "Principal",
    location: "Remote",
    skill: "Azure IoT, MQTT, Edge Computing",
    fulfillment: "Internal",
    status: "Open",
    externalReqId: "JJ-IOT-77",
    createDate: "2026-02-01",
    notes: ""
  },
  {
    id: 21,
    priority: "Medium",
    type: "Closed Won - Extension",
    client: "Amazon.com, Inc.",
    opportunity: "Warehouse Robotics",
    probability: 100,
    estStartDate: "2026-03-15",
    estEndDate: "2026-09-15",
    serviceLine: "App Dev",
    practice: "Retail",
    deliveryUnit: "Retail & Consumer",
    role: "C++ Developer",
    careerLevel: "Sr",
    location: "India",
    skill: "C++, ROS, Algorithms",
    fulfillment: "Internal",
    status: "Open",
    externalReqId: "AMZ-ROBO-21",
    createDate: "2026-01-25",
    notes: ""
  },
  {
    id: 22,
    priority: "Urgent",
    type: "Existing - Attrition",
    client: "Ford Motor Company",
    opportunity: "Dealer Management System",
    probability: 100,
    estStartDate: "2026-02-15",
    estEndDate: "2026-08-15",
    serviceLine: "Management",
    practice: "Auto",
    deliveryUnit: "Auto & Industrials",
    role: "Scrum Master",
    careerLevel: "Manager",
    location: "US",
    skill: "Agile, Jira, CSM",
    fulfillment: "External",
    status: "Open",
    externalReqId: "FORD-SM-11",
    createDate: "2026-02-03",
    notes: "Must be onsite in Detroit"
  },
  {
    id: 23,
    priority: "High",
    type: "Pipeline - New Work",
    client: "Citibank",
    opportunity: "Fraud Detection AI",
    probability: 75,
    estStartDate: "2026-04-01",
    estEndDate: "2026-10-01",
    serviceLine: "Data",
    practice: "Banking",
    deliveryUnit: "BFSI",
    role: "ML Engineer",
    careerLevel: "Sr",
    location: "India",
    skill: "Python, TensorFlow, Hadoop",
    fulfillment: "Internal",
    status: "Open",
    externalReqId: "",
    createDate: "2026-02-04",
    notes: ""
  },
  {
    id: 24,
    priority: "Low",
    type: "Existing - New Roles",
    client: "Meta Platforms, Inc.",
    opportunity: "Internal HR Tool",
    probability: 90,
    estStartDate: "2026-03-01",
    estEndDate: "2026-06-01",
    serviceLine: "App Dev",
    practice: "Retail",
    deliveryUnit: "TMT",
    role: "React Native Developer",
    careerLevel: "Jr",
    location: "Remote",
    skill: "React Native, TypeScript",
    fulfillment: "Internal",
    status: "Open",
    externalReqId: "META-HR-05",
    createDate: "2026-02-01",
    notes: ""
  },
  {
    id: 25,
    priority: "Medium",
    type: "Closed Won - New Work",
    client: "Wells Fargo & Company",
    opportunity: "Commercial Lending Portal",
    probability: 100,
    estStartDate: "2026-03-15",
    estEndDate: "2026-12-15",
    serviceLine: "QA",
    practice: "Banking",
    deliveryUnit: "BFSI",
    role: "QA Lead",
    careerLevel: "Lead",
    location: "India",
    skill: "Automation, Performance Testing",
    fulfillment: "Internal",
    status: "Open",
    externalReqId: "WF-QA-99",
    createDate: "2026-01-20",
    notes: ""
  }
];

module.exports = { POSITIONS_DATA };